### ISSUE TITLE
HQ crashes when the Wekan API can't be created

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-report#145]
2017-11-09 17:15:25,224:ERROR:Couldn't create API for Wekan at http://www.wekan<url> for user <user>: 'token'
Traceback (most recent call last):
  File "hq-src/backend/quality_report.py", line 104, in <module>
    report = Reporter(args.project).create_report(args.report)
  File "hq-src/backend/quality_report.py", line 41, in create_report
    history.add_report(quality_report)
  File "/var/jenkins/workspace/hq-test/hq-src/backend/hqlib/metric_source/history.py", line 77, in add_report
    self.add_metrics(quality_report.date(), quality_report.metrics())
  File "/var/jenkins/workspace/hq-test/hq-src/backend/hqlib/metric_source/history.py", line 87, in add_metrics
    value = metric.numerical_value()
  File "/var/jenkins/workspace/hq-test/hq-src/backend/hqlib/domain/measurement/metric.py", line 299, in numerical_value
    value = self.value()
  File "/var/jenkins/workspace/hq-test/hq-src/backend/hqlib/metric/project/project_management_metrics.py", line 32, in value
    return -1 if self._missing() else (datetime.datetime.now() - self._metric_source.datetime()).days
  File "/var/jenkins/workspace/hq-test/hq-src/backend/hqlib/metric/project/project_management_metrics.py", line 35, in _missing
    return self._metric_source.datetime() in (None, datetime.datetime.min)
  File "/var/jenkins/workspace/hq-test/hq-src/backend/hqlib/metric_source/issue_log/wekan.py", line 47, in datetime
    for card in self.__cards():
  File "/var/jenkins/workspace/hq-test/hq-src/backend/hqlib/metric_source/issue_log/wekan.py", line 136, in __cards
    for cards_list in self.__board().get_cardslists():
AttributeError: 'NoneType' object has no attribute 'get_cardslists'

**Comment by fniessink** [comment]
Should be fixed in 2.14.2.
