### ISSUE TITLE
URLError during handling OSError crashes HQ

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-report#495]
2018-09-07 10:57:49,854:WARNING:Couldn't open http://www.jenkins.project.org/job/component-OWASP-dependencychecker/lastSuccessfulBuild/dependency-check-jenkins-pluginResult/tab.files/file.1205009409/HIGH/tab.types/: <urlopen error [Errno 113] Host is unreachable>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/quality_report.py", line 122, in <module>
    report = Reporter(args.project).create_report(args.report, args.frontend != 'no')
  File "/usr/local/bin/quality_report.py", line 45, in create_report
    self.__create_report(quality_report, report_folder, create_frontend)
  File "/usr/local/bin/quality_report.py", line 60, in __create_report
    cls.__create_json_file(quality_report, report_dir, formatter, filename)
  File "/usr/local/bin/quality_report.py", line 68, in __create_json_file
    cls.__format_and_write_report(quality_report, formatter, json_filename, 'w', 'utf-8')
  File "/usr/local/bin/quality_report.py", line 113, in __format_and_write_report
    formatted_report = report_formatter(**kwargs).process(quality_report)
  File "/usr/local/lib/python3.7/site-packages/hqlib/formatting/base_formatter.py", line 33, in process
    parts = [self.prefix(report), self.body(report), self.postfix()]
  File "/usr/local/lib/python3.7/site-packages/hqlib/formatting/base_formatter.py", line 47, in body
    sections.append(self.section(section))
  File "/usr/local/lib/python3.7/site-packages/hqlib/formatting/base_formatter.py", line 54, in section
    metrics.append(self.metric(metric))
  File "/usr/local/lib/python3.7/site-packages/hqlib/formatting/json_formatter.py", line 128, in metric
    data = self.__metric_data(metric)
  File "/usr/local/lib/python3.7/site-packages/hqlib/formatting/json_formatter.py", line 137, in __metric_data
    extra_info = metric.extra_info()
  File "/usr/local/lib/python3.7/site-packages/hqlib/domain/measurement/metric.py", line 377, in extra_info
    url_list = self.extra_info_rows()
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric/product/owasp_dependency_metrics.py", line 43, in extra_info_rows
    dependencies += self._metric_source.get_dependencies_info(metric_id, self.risk_level_key)
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric_source/owasp_dependency_report/jenkins_owasp_dependency_plugin.py", line 51, in get_dependencies_info
    cves = self._get_cves(self.__report_html_file_list.format(job=metric_source_id) + link, priority)
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric_source/owasp_dependency_report/jenkins_owasp_dependency_plugin.py", line 60, in _get_cves
    soup = self._get_soup(url.rstrip('/') + '/' + priority.upper() + '/tab.types/')
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric_source/owasp_dependency_report/jenkins_owasp_dependency_plugin.py", line 101, in _get_soup
    return bs4.BeautifulSoup(self.url_open(url), "lxml")
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric_source/ci_server/jenkins.py", line 199, in url_open
    return self.__url_opener.url_open(urllib.parse.quote(url, safe="%/:=&?~#+!$,;'@()*[]"), log_error=log_error)
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric_source/url_opener.py", line 116, in url_open
    return self.__opener(url)
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] Host is unreachable>
Build step 'Execute shell' marked build as failure

**Comment by milenk** [comment]
solved together with https://github.com/ICTU/quality-report/issues/551
