### ISSUE TITLE
Unhandled exception when Checkmarx returns empty JSON

### ISSUE THREAD

**Issue by fniessink** [ICTU/quality-report#496]
2018-09-07 13:57:14,283:WARNING:Couldn't open https://checkmarx.url//Cxwebinterface/odata/v1/Projects?$expand=LastScan&$filter=Name%20eq%20%27project-id%27: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/usr/local/bin/quality_report.py", line 122, in <module>
    report = Reporter(args.project).create_report(args.report, args.frontend != 'no')
  File "/usr/local/bin/quality_report.py", line 44, in create_report
    history.add_report(quality_report)
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric_source/history.py", line 102, in add_report
    self.add_metrics(quality_report.date(), quality_report.metrics())
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric_source/history.py", line 111, in add_metrics
    value = metric.numerical_value()
  File "/usr/local/lib/python3.7/site-packages/hqlib/domain/measurement/metric.py", line 366, in numerical_value
    value = self.value()
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric/product/alerts_metrics.py", line 35, in value
    return -1 if self._missing() else self._nr_alerts()
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric/product/alerts_metrics.py", line 38, in _missing
    return self._nr_alerts() < 0
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric/product/checkmarx_metrics.py", line 33, in _nr_alerts
    return self._metric_source.nr_warnings(tuple(ids), self.risk_level_key) if self._metric_source else -1
  File "/usr/local/lib/python3.7/site-packages/hqlib/metric_source/checkmarx.py", line 61, in nr_warnings
    nr_alerts += json[priority.title()]
TypeError: 'NoneType' object is not subscriptable

**Comment by milenk** [comment]
Code changed with https://github.com/ICTU/quality-report/issues/534 so, the finding is not applicabke any more.
